"""
SQLAlchemy Database Models for Mini NOC.
Defines all tables: devices, metrics, alerts, scan_logs, audit_logs.
"""

from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, 
    ForeignKey, Text, Enum, Index
)
from sqlalchemy.orm import relationship

# Fix relative import: session.py is in parent directory (app.db)
from ..session import Base

# Import new models
from .audit import AuditLog

class DeviceStatus(str, PyEnum):
    """Device availability status."""
    UP = "UP"
    DOWN = "DOWN"
    DEGRADED = "DEGRADED"
    UNKNOWN = "UNKNOWN"


class DeviceType(str, PyEnum):
    """Type of network device."""
    ROUTER = "ROUTER"
    SWITCH = "SWITCH"
    SERVER = "SERVER"
    ACCESS_POINT = "ACCESS_POINT"
    FIREWALL = "FIREWALL"
    OTHER = "OTHER"


class AlertSeverity(str, PyEnum):
    """Alert severity levels."""
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class Device(Base):
    """
    Network device being monitored.
    Stores device identification and current status.
    """
    __tablename__ = "devices"
    
    id = Column(Integer, primary_key=True, index=True)
    ip_address = Column(String(45), unique=True, nullable=False, index=True)
    hostname = Column(String(255), nullable=True)
    device_type = Column(Enum(DeviceType), default=DeviceType.OTHER)
    description = Column(Text, nullable=True)
    
    # Enhanced Discovery Fields
    mac_address = Column(String(17), nullable=True)  # Format: XX:XX:XX:XX:XX:XX
    vendor = Column(String(100), nullable=True)  # Manufacturer from OUI
    os_type = Column(String(50), nullable=True)  # Windows, Linux, etc.
    open_ports = Column(Text, nullable=True)  # JSON array of open ports
    
    # SNMP Configuration
    snmp_community = Column(String(64), default="public")
    snmp_port = Column(Integer, default=161)
    
    # Current Status
    status = Column(Enum(DeviceStatus), default=DeviceStatus.UNKNOWN)
    last_seen = Column(DateTime, nullable=True)
    consecutive_failures = Column(Integer, default=0)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Monitoring toggle
    is_active = Column(Boolean, default=True)
    
    # Relationships
    metrics = relationship("Metric", back_populates="device", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="device", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Device(ip={self.ip_address}, status={self.status})>"


class Metric(Base):
    """
    Performance metrics collected from devices.
    Stores latency, packet loss, and SNMP data.
    """
    __tablename__ = "metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("devices.id", ondelete="CASCADE"), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    # ICMP Metrics
    latency_ms = Column(Float, nullable=True)
    packet_loss_percent = Column(Float, nullable=True)
    packets_sent = Column(Integer, nullable=True)
    packets_received = Column(Integer, nullable=True)
    
    # SNMP Metrics
    cpu_usage_percent = Column(Float, nullable=True)
    memory_usage_percent = Column(Float, nullable=True)
    uptime_seconds = Column(Integer, nullable=True)
    
    # Relationship
    device = relationship("Device", back_populates="metrics")
    
    # Composite index for efficient querying
    __table_args__ = (
        Index("idx_metrics_device_timestamp", "device_id", "timestamp"),
    )
    
    def __repr__(self):
        return f"<Metric(device_id={self.device_id}, latency={self.latency_ms}ms)>"


class Alert(Base):
    """
    Alerts generated by fault detection.
    Tracks issues, severity, and resolution status.
    """
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("devices.id", ondelete="CASCADE"), nullable=False)
    
    # Alert Details
    severity = Column(Enum(AlertSeverity), default=AlertSeverity.INFO)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=True)
    metric_type = Column(String(50), nullable=True)  # latency, packet_loss, cpu, etc.
    metric_value = Column(Float, nullable=True)
    threshold_value = Column(Float, nullable=True)
    
    # Status
    is_resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationship
    device = relationship("Device", back_populates="alerts")
    
    def __repr__(self):
        return f"<Alert(device_id={self.device_id}, severity={self.severity}, resolved={self.is_resolved})>"


class ScanLog(Base):
    """
    Audit log for all scanning operations.
    Records scan events for operational visibility.
    """
    __tablename__ = "scan_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    action = Column(String(50), nullable=False)  # DISCOVERY, HEALTH_CHECK, SNMP_POLL
    details = Column(Text, nullable=True)
    
    # Scan Results
    devices_scanned = Column(Integer, nullable=True)
    devices_up = Column(Integer, nullable=True)
    devices_down = Column(Integer, nullable=True)
    duration_seconds = Column(Float, nullable=True)
    
    # Status
    success = Column(Boolean, default=True)
    error_message = Column(Text, nullable=True)
    
    def __repr__(self):
        return f"<ScanLog(action={self.action}, timestamp={self.timestamp})>"


class IncidentStatus(str, PyEnum):
    """Incident lifecycle status."""
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    IDENTIFIED = "IDENTIFIED"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"


class IncidentPriority(str, PyEnum):
    """Incident priority levels."""
    P1 = "P1"  # Critical - Full outage
    P2 = "P2"  # High - Major degradation
    P3 = "P3"  # Medium - Partial issues
    P4 = "P4"  # Low - Minor issues


class Incident(Base):
    """
    Incident management for tracking network issues.
    Groups related alerts and tracks resolution timeline.
    """
    __tablename__ = "incidents"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Incident Details
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    status = Column(Enum(IncidentStatus), default=IncidentStatus.OPEN)
    priority = Column(Enum(IncidentPriority), default=IncidentPriority.P3)
    
    # Affected Systems
    affected_devices = Column(Text, nullable=True)  # JSON array of device IDs
    impact_summary = Column(Text, nullable=True)
    
    # Root Cause
    root_cause = Column(Text, nullable=True)
    resolution = Column(Text, nullable=True)
    
    # Timeline
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)
    
    # Owner/Assignee
    created_by = Column(String(100), nullable=True)
    assigned_to = Column(String(100), nullable=True)
    
    # Relationships
    updates = relationship("IncidentUpdate", back_populates="incident", cascade="all, delete-orphan")
    linked_alerts = relationship("IncidentAlert", back_populates="incident", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Incident(id={self.id}, title='{self.title}', status={self.status})>"


class IncidentUpdate(Base):
    """
    Timeline updates for incidents.
    Records investigation progress and status changes.
    """
    __tablename__ = "incident_updates"
    
    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    
    # Update Details
    message = Column(Text, nullable=False)
    update_type = Column(String(50), default="update")  # update, status_change, assignment
    previous_status = Column(String(50), nullable=True)
    new_status = Column(String(50), nullable=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    created_by = Column(String(100), nullable=True)
    
    # Relationship
    incident = relationship("Incident", back_populates="updates")
    
    def __repr__(self):
        return f"<IncidentUpdate(incident_id={self.incident_id}, type={self.update_type})>"


class IncidentAlert(Base):
    """
    Links alerts to incidents.
    Many-to-many relationship between incidents and alerts.
    """
    __tablename__ = "incident_alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    alert_id = Column(Integer, ForeignKey("alerts.id", ondelete="CASCADE"), nullable=False)
    linked_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationship
    incident = relationship("Incident", back_populates="linked_alerts")
    
    __table_args__ = (
        Index("idx_incident_alert", "incident_id", "alert_id", unique=True),
    )

